- id: export-requirements-docs
  name: Convert pyproject.toml to requirements.txt
  description: Generate requirements.txt pyproject.toml for backwards compatibility with dev requirements.
  language: system
  entry: poetry export -E docs -f requirements.txt -o requirements.txt --without-hashes
  files: "^pyproject.toml$"
  pass_filenames: false
