site_name: typical
site_author: Sean D Stewart
copyright: "Copyright &copy; 2019 - 2020 Sean Stewart"
site_url: https://python-typical.org
repo_url: https://github.com/seandstewart/typical
repo_name: seandstewart/typical
theme:
  name: "material"
  favicon: "static/favicon/favicon.ico"
  logo: "static/c3p-white.png"
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: "teal"
      accent: "amber"
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: "cyan"
      accent: "amber"
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  font:
    text: "IBM Plex Serif"
    code: "IBM Plex Mono"
plugins:
  - search
  - awesome-pages
markdown_extensions:
  - toc:
      permalink: "🔖"
  - smarty
  - admonition
  - footnotes
  - codehilite
  - pymdownx.arithmatex
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
extra:
  social:
    - icon: "fontawesome/brands/github-alt"
      link: "https://github.com/seandstewart/typical"
    - icon: "fontawesome/brands/twitter"
      link: "https://twitter.com/MrSeanStewart"
    - icon: "fontawesome/brands/linkedin"
      link: "https://linkedin.com/in/seandstewart"
  manifest: "img/favicon/site.webmanifest"
